fix drush path

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -90,7 +90,7 @@ jobs:
             
             # Database Backup (Safety First)
             mkdir -p $SHARED_PATH/backups
-            $PHP_BIN vendor/bin/drush/drush.php sql:dump --quiet --gzip --extra-dump=--no-tablespaces --result-file=${{ env.SHARED_PATH }}/backups/pre-deploy-$(date +%F-%H%M).sql
+            $PHP_BIN vendor/bin/drush.php sql:dump --quiet --gzip --extra-dump=--no-tablespaces --result-file=${{ env.SHARED_PATH }}/backups/pre-deploy-$(date +%F-%H%M).sql
 
             # DELETE OLD BACKUPS (Older than 7 days)
             # This finds files in the backup dir ending in .sql.gz and removes them if they are 7+ days old
@@ -111,9 +111,9 @@ jobs:
             DEPLOY_INFO="$(echo ${{ github.sha }} | cut -c1-7) on $(date +'%Y-%m-%d %H:%M')"
             echo "DEBUG: DEPLOY_INFO is set to: '$DEPLOY_INFO'"
             echo "DEBUG: Running drush state:set system.deployment_revision '$DEPLOY_INFO'"
-            $PHP_BIN vendor/bin/drush/drush.php state:set system.deployment_revision "$DEPLOY_INFO" --format=string --quiet
+            $PHP_BIN vendor/bin/drush.php state:set system.deployment_revision "$DEPLOY_INFO" --format=string --quiet
             # Verify it immediately
-            $PHP_BIN vendor/bin/drush/drush.php state:get system.deployment_revision || echo "State get failed!"
+            $PHP_BIN vendor/bin/drush.php state:get system.deployment_revision || echo "State get failed!"
 
             # Drupal Deploy Sequence
-            $PHP_BIN vendor/bin/drush/drush.php -l $URI deploy -y
+            $PHP_BIN vendor/bin/drush.php -l $URI deploy -y
